### ISSUE TITLE
Spatial Crafting's item holding blocks can be removed with water

### ISSUE THREAD

**Issue by ghost** [natanfudge/SpatialCrafting#7]
Before water: ![image](https://user-images.githubusercontent.com/5214513/70378770-44aa1f80-191c-11ea-9a22-286ba2d818dc.png)
After water: 
![image](https://user-images.githubusercontent.com/5214513/70378779-62778480-191c-11ea-852e-d274ab381b1b.png)

**Comment by natanfudge** [comment]
[yes](https://github.com/FabricMC/fabric/issues/456)

**Comment by natanfudge** [comment]
I guess holograms are made of structure void now (fixed).
